{"name": "test_foo[3-0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 3", "trace": "x = 0, y = 3\n\n    @pytest.mark.parametrize('x', [0,1])\n    @pytest.mark.parametrize('y', [2,3])\n    def test_foo(x,y):\n>       assert  x == y\nE       assert 0 == 3\n\nmain.py:41: AssertionError"}, "parameters": [{"name": "y", "value": "3"}, {"name": "x", "value": "0"}], "start": 1659171559283, "stop": 1659171559283, "uuid": "b26b1aee-b02c-40f0-b755-d678931d2583", "historyId": "59dbe799bc883106a0c75c421d9db971", "testCaseId": "526d577031aefc12bfe891bf0bd6f968", "fullName": "main#test_foo", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "MacBook-Pro-Eugene.local"}, {"name": "thread", "value": "3565-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}