{"name": "test_foo[3-1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 3", "trace": "x = 1, y = 3\n\n    @pytest.mark.parametrize('x', [0,1])\n    @pytest.mark.parametrize('y', [2,3])\n    def test_foo(x,y):\n>       assert  x == y\nE       assert 1 == 3\n\nmain.py:43: AssertionError"}, "parameters": [{"name": "y", "value": "3"}, {"name": "x", "value": "1"}], "start": 1659171729185, "stop": 1659171729185, "uuid": "075f7c33-5981-4ad9-907b-66fe764aff9c", "historyId": "22196ed4da9868d4b19f2d8f607e02e2", "testCaseId": "526d577031aefc12bfe891bf0bd6f968", "fullName": "main#test_foo", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "MacBook-Pro-Eugene.local"}, {"name": "thread", "value": "3652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}