{"name": "test_foo[2-1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "x = 1, y = 2\n\n    @pytest.mark.parametrize('x', [0,1])\n    @pytest.mark.parametrize('y', [2,3])\n    def test_foo(x,y):\n>       assert  x == y\nE       assert 1 == 2\n\nmain.py:43: AssertionError"}, "parameters": [{"name": "y", "value": "2"}, {"name": "x", "value": "1"}], "start": 1659171729162, "stop": 1659171729162, "uuid": "473115e1-4aa1-4312-b5de-32acb9974399", "historyId": "33646b3e64f2563e02c41101831299bb", "testCaseId": "526d577031aefc12bfe891bf0bd6f968", "fullName": "main#test_foo", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "MacBook-Pro-Eugene.local"}, {"name": "thread", "value": "3652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}