{"name": "test_foo[2-0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0 == 2", "trace": "x = 0, y = 2\n\n    @pytest.mark.parametrize('x', [0,1])\n    @pytest.mark.parametrize('y', [2,3])\n    def test_foo(x,y):\n>       assert  x == y\nE       assert 0 == 2\n\nmain.py:43: AssertionError"}, "parameters": [{"name": "y", "value": "2"}, {"name": "x", "value": "0"}], "start": 1659171729149, "stop": 1659171729149, "uuid": "687675a9-f686-4717-9cd6-23f4e6ac6830", "historyId": "8f32a0bafe670117d9d5fc908b6af691", "testCaseId": "526d577031aefc12bfe891bf0bd6f968", "fullName": "main#test_foo", "labels": [{"name": "suite", "value": "main"}, {"name": "host", "value": "MacBook-Pro-Eugene.local"}, {"name": "thread", "value": "3652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "main"}]}